import { User, LabResult } from "@/types"

/**
 * Mock Patient Data
 * Healthcare-oriented realistic data for HMS patient management
 */

export interface MockPrescription {
  id: string
  medicationName: string
  dosage: string
  frequency: string
  duration: string
  prescribingDoctor: string
  status: "active" | "completed" | "refilling" | "cancelled"
  startDate: string
  endDate?: string
  instructions?: string
}

export interface MockMedicalHistoryEvent {
  type: "allergy" | "condition" | "surgery" | "medication"
  title: string
  description: string
  date: string
  severity?: "mild" | "moderate" | "severe"
}

// Mock Patients Database
export const mockPatients: User[] = [
  {
    _id: "patient-001",
    name: "Robert Johnson",
    email: "robert.johnson@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Robert",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-01-15T08:30:00Z",
    updatedAt: "2024-05-20T14:22:00Z",
    status: "in_treatment",
    banned: false,
    gender: "Male",
    age: "45",
    bloodgroup: "O+",
    medicalHistory: "Hypertension, Type 2 Diabetes",
    department: "Cardiology",
    assignedDoctorId: "doc-001",
    assignedDoctorName: "Dr. Sarah Mitchell",
    assignedNurseId: "nurse-001",
    assignedNurseName: "Emily Watson",
  },
  {
    _id: "patient-002",
    name: "Patricia Garcia",
    email: "patricia.garcia@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-02-10T09:15:00Z",
    updatedAt: "2024-05-21T11:45:00Z",
    status: "admitted",
    banned: false,
    gender: "Female",
    age: "38",
    bloodgroup: "A-",
    medicalHistory: "Asthma, Allergies",
    department: "Pulmonology",
    assignedDoctorId: "doc-002",
    assignedDoctorName: "Dr. James Wilson",
    assignedNurseId: "nurse-002",
    assignedNurseName: "Maria Santos",
  },
  {
    _id: "patient-003",
    name: "Michael Chen",
    email: "michael.chen@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-01-28T07:20:00Z",
    updatedAt: "2024-05-22T09:10:00Z",
    status: "observation",
    banned: false,
    gender: "Male",
    age: "52",
    bloodgroup: "B+",
    medicalHistory: "Arthritis, Hypertension",
    department: "Orthopedics",
    assignedDoctorId: "doc-003",
    assignedDoctorName: "Dr. Lisa Anderson",
    assignedNurseId: "nurse-003",
    assignedNurseName: "James Brown",
  },
  {
    _id: "patient-004",
    name: "Jennifer Martinez",
    email: "jennifer.martinez@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-05-19T16:30:00Z",
    status: "follow_up",
    banned: false,
    gender: "Female",
    age: "34",
    bloodgroup: "AB+",
    medicalHistory: "Migraine, Anxiety",
    department: "Neurology",
    assignedDoctorId: "doc-004",
    assignedDoctorName: "Dr. David Kumar",
    assignedNurseId: "nurse-001",
    assignedNurseName: "Emily Watson",
  },
  {
    _id: "patient-005",
    name: "Thomas Williams",
    email: "thomas.williams@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Thomas",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-02-20T08:45:00Z",
    updatedAt: "2024-05-21T13:15:00Z",
    status: "in_treatment",
    banned: false,
    gender: "Male",
    age: "41",
    bloodgroup: "O-",
    medicalHistory: "Gastritis, GERD",
    department: "Gastroenterology",
    assignedDoctorId: "doc-005",
    assignedDoctorName: "Dr. Rachel Green",
    assignedNurseId: "nurse-002",
    assignedNurseName: "Maria Santos",
  },
  {
    _id: "patient-006",
    name: "Angela Lopez",
    email: "angela.lopez@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Angela",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-01-08T06:30:00Z",
    updatedAt: "2024-05-22T10:20:00Z",
    status: "discharged",
    banned: false,
    gender: "Female",
    age: "29",
    bloodgroup: "B-",
    medicalHistory: "Thyroid disorder",
    department: "Endocrinology",
    assignedDoctorId: "doc-006",
    assignedDoctorName: "Dr. Michael Torres",
    assignedNurseId: "nurse-003",
    assignedNurseName: "James Brown",
  },
  {
    _id: "patient-007",
    name: "David Lee",
    email: "david.lee@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-03-12T09:00:00Z",
    updatedAt: "2024-05-20T15:45:00Z",
    status: "admitted",
    banned: false,
    gender: "Male",
    age: "56",
    bloodgroup: "A+",
    medicalHistory: "Heart disease, High cholesterol",
    department: "Cardiology",
    assignedDoctorId: "doc-001",
    assignedDoctorName: "Dr. Sarah Mitchell",
    assignedNurseId: "nurse-001",
    assignedNurseName: "Emily Watson",
  },
  {
    _id: "patient-008",
    name: "Susan Brown",
    email: "susan.brown@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Susan",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-02-03T07:15:00Z",
    updatedAt: "2024-05-21T12:30:00Z",
    status: "observation",
    banned: false,
    gender: "Female",
    age: "47",
    bloodgroup: "O+",
    medicalHistory: "Diabetes, Kidney disease",
    department: "Nephrology",
    assignedDoctorId: "doc-007",
    assignedDoctorName: "Dr. Christopher Bell",
    assignedNurseId: "nurse-002",
    assignedNurseName: "Maria Santos",
  },
  {
    _id: "patient-009",
    name: "Christopher Davis",
    email: "christopher.davis@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Christopher",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-01-22T08:00:00Z",
    updatedAt: "2024-05-22T14:00:00Z",
    status: "in_treatment",
    banned: false,
    gender: "Male",
    age: "39",
    bloodgroup: "AB-",
    medicalHistory: "Fracture recovery",
    department: "Orthopedics",
    assignedDoctorId: "doc-003",
    assignedDoctorName: "Dr. Lisa Anderson",
    assignedNurseId: "nurse-003",
    assignedNurseName: "James Brown",
  },
  {
    _id: "patient-010",
    name: "Rebecca White",
    email: "rebecca.white@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rebecca",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-03-18T10:30:00Z",
    updatedAt: "2024-05-19T11:20:00Z",
    status: "follow_up",
    banned: false,
    gender: "Female",
    age: "35",
    bloodgroup: "B+",
    medicalHistory: "Post-surgery recovery",
    department: "Surgery",
    assignedDoctorId: "doc-008",
    assignedDoctorName: "Dr. Emily Rodriguez",
    assignedNurseId: "nurse-001",
    assignedNurseName: "Emily Watson",
  },
  {
    _id: "patient-011",
    name: "James Thompson",
    email: "james.thompson@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-02-25T09:45:00Z",
    updatedAt: "2024-05-20T16:00:00Z",
    status: "admitted",
    banned: false,
    gender: "Male",
    age: "62",
    bloodgroup: "A-",
    medicalHistory: "COPD, Smoking history",
    department: "Pulmonology",
    assignedDoctorId: "doc-002",
    assignedDoctorName: "Dr. James Wilson",
    assignedNurseId: "nurse-002",
    assignedNurseName: "Maria Santos",
  },
  {
    _id: "patient-012",
    name: "Laura Harris",
    email: "laura.harris@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Laura",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-03-30T07:00:00Z",
    updatedAt: "2024-05-21T09:30:00Z",
    status: "observation",
    banned: false,
    gender: "Female",
    age: "51",
    bloodgroup: "O+",
    medicalHistory: "Hypertension, Obesity",
    department: "Cardiology",
    assignedDoctorId: "doc-001",
    assignedDoctorName: "Dr. Sarah Mitchell",
    assignedNurseId: "nurse-003",
    assignedNurseName: "James Brown",
  },
  {
    _id: "patient-013",
    name: "Richard Anderson",
    email: "richard.anderson@email.com",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Richard",
    role: "patient",
    emailVerified: true,
    createdAt: "2024-01-05T08:20:00Z",
    updatedAt: "2024-05-22T13:45:00Z",
    status: "in_treatment",
    banned: false,
    gender: "Male",
    age: "44",
    bloodgroup: "B+",
    medicalHistory: "Prostate issues",
    department: "Urology",
    assignedDoctorId: "doc-009",
    assignedDoctorName: "Dr. Anthony Martinez",
    assignedNurseId: "nurse-001",
    assignedNurseName: "Emily Watson",
  },
]

// Mock Prescriptions Database
export const mockPrescriptions: Record<string, MockPrescription[]> = {
  "patient-001": [
    {
      id: "rx-001-01",
      medicationName: "Lisinopril",
      dosage: "10mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-04-10",
      instructions: "Take in the morning with or without food",
    },
    {
      id: "rx-001-02",
      medicationName: "Metformin",
      dosage: "500mg",
      frequency: "Twice daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-03-15",
      instructions: "Take with meals",
    },
    {
      id: "rx-001-03",
      medicationName: "Atorvastatin",
      dosage: "20mg",
      frequency: "Once at bedtime",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-02-01",
      instructions: "Take in the evening",
    },
    {
      id: "rx-001-04",
      medicationName: "Aspirin",
      dosage: "81mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "completed",
      startDate: "2024-01-20",
      endDate: "2024-05-15",
      instructions: "Take in the morning",
    },
  ],
  "patient-002": [
    {
      id: "rx-002-01",
      medicationName: "Albuterol Inhaler",
      dosage: "90mcg",
      frequency: "As needed",
      duration: "Ongoing",
      prescribingDoctor: "Dr. James Wilson",
      status: "active",
      startDate: "2024-02-10",
      instructions: "Use 1-2 puffs when experiencing shortness of breath",
    },
    {
      id: "rx-002-02",
      medicationName: "Fluticasone/Salmeterol",
      dosage: "250/50mcg",
      frequency: "Twice daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. James Wilson",
      status: "active",
      startDate: "2024-02-15",
      instructions: "Rinse mouth after use",
    },
    {
      id: "rx-002-03",
      medicationName: "Loratadine",
      dosage: "10mg",
      frequency: "Once daily",
      duration: "3 months",
      prescribingDoctor: "Dr. James Wilson",
      status: "active",
      startDate: "2024-05-01",
      instructions: "Take as needed for allergies",
    },
  ],
  "patient-003": [
    {
      id: "rx-003-01",
      medicationName: "Ibuprofen",
      dosage: "400mg",
      frequency: "Three times daily",
      duration: "2 weeks",
      prescribingDoctor: "Dr. Lisa Anderson",
      status: "active",
      startDate: "2024-05-15",
      instructions: "Take with food",
    },
    {
      id: "rx-003-02",
      medicationName: "Lisinopril",
      dosage: "5mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Lisa Anderson",
      status: "active",
      startDate: "2024-01-10",
      instructions: "Monitor blood pressure regularly",
    },
    {
      id: "rx-003-03",
      medicationName: "Calcium Supplement",
      dosage: "1000mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Lisa Anderson",
      status: "refilling",
      startDate: "2024-03-01",
      instructions: "Take with food for better absorption",
    },
  ],
  "patient-004": [
    {
      id: "rx-004-01",
      medicationName: "Sumatriptan",
      dosage: "50mg",
      frequency: "As needed",
      duration: "Ongoing",
      prescribingDoctor: "Dr. David Kumar",
      status: "active",
      startDate: "2024-02-05",
      instructions: "Take at first sign of migraine",
    },
    {
      id: "rx-004-02",
      medicationName: "Sertraline",
      dosage: "50mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. David Kumar",
      status: "active",
      startDate: "2024-01-15",
      instructions: "Take in morning, may cause drowsiness",
    },
    {
      id: "rx-004-03",
      medicationName: "Propranolol",
      dosage: "40mg",
      frequency: "Twice daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. David Kumar",
      status: "completed",
      startDate: "2024-03-01",
      endDate: "2024-04-30",
    },
  ],
  "patient-005": [
    {
      id: "rx-005-01",
      medicationName: "Omeprazole",
      dosage: "20mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Rachel Green",
      status: "active",
      startDate: "2024-01-20",
      instructions: "Take 30 minutes before meals",
    },
    {
      id: "rx-005-02",
      medicationName: "Ranitidine",
      dosage: "150mg",
      frequency: "Twice daily",
      duration: "4 weeks",
      prescribingDoctor: "Dr. Rachel Green",
      status: "active",
      startDate: "2024-05-01",
      instructions: "Take with meals",
    },
    {
      id: "rx-005-03",
      medicationName: "Antacid",
      dosage: "500mg",
      frequency: "As needed",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Rachel Green",
      status: "active",
      startDate: "2024-02-10",
      instructions: "Use for immediate relief",
    },
    {
      id: "rx-005-04",
      medicationName: "Probiotic",
      dosage: "1 capsule",
      frequency: "Once daily",
      duration: "8 weeks",
      prescribingDoctor: "Dr. Rachel Green",
      status: "active",
      startDate: "2024-04-15",
      instructions: "Take in morning on empty stomach",
    },
  ],
  "patient-006": [
    {
      id: "rx-006-01",
      medicationName: "Levothyroxine",
      dosage: "50mcg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Michael Torres",
      status: "active",
      startDate: "2024-02-01",
      instructions: "Take 30 minutes before breakfast",
    },
    {
      id: "rx-006-02",
      medicationName: "Multivitamin",
      dosage: "1 tablet",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Michael Torres",
      status: "active",
      startDate: "2024-03-10",
      instructions: "Take with breakfast",
    },
  ],
  "patient-007": [
    {
      id: "rx-007-01",
      medicationName: "Clopidogrel",
      dosage: "75mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-04-01",
      instructions: "Do not skip doses",
    },
    {
      id: "rx-007-02",
      medicationName: "Metoprolol",
      dosage: "50mg",
      frequency: "Twice daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-03-15",
      instructions: "Monitor pulse and blood pressure",
    },
    {
      id: "rx-007-03",
      medicationName: "Furosemide",
      dosage: "40mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-04-10",
      instructions: "Take in morning to avoid nocturia",
    },
    {
      id: "rx-007-04",
      medicationName: "Nitroglycerine",
      dosage: "0.3mg",
      frequency: "As needed",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "refilling",
      startDate: "2024-04-20",
      instructions: "Use under tongue for chest pain",
    },
  ],
  "patient-008": [
    {
      id: "rx-008-01",
      medicationName: "Insulin Glargine",
      dosage: "20 units",
      frequency: "Once at bedtime",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Christopher Bell",
      status: "active",
      startDate: "2024-01-05",
      instructions: "Inject subcutaneously",
    },
    {
      id: "rx-008-02",
      medicationName: "ACE Inhibitor",
      dosage: "10mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Christopher Bell",
      status: "active",
      startDate: "2024-02-01",
      instructions: "Monitor kidney function",
    },
    {
      id: "rx-008-03",
      medicationName: "Phosphate Binder",
      dosage: "667mg",
      frequency: "Three times daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Christopher Bell",
      status: "active",
      startDate: "2024-01-20",
      instructions: "Take with meals",
    },
  ],
  "patient-009": [
    {
      id: "rx-009-01",
      medicationName: "Oxycodone",
      dosage: "5mg",
      frequency: "Every 4-6 hours",
      duration: "4 weeks",
      prescribingDoctor: "Dr. Lisa Anderson",
      status: "active",
      startDate: "2024-05-10",
      instructions: "Use as needed for pain, may cause drowsiness",
    },
    {
      id: "rx-009-02",
      medicationName: "Physiotherapy",
      dosage: "N/A",
      frequency: "3 times weekly",
      duration: "8 weeks",
      prescribingDoctor: "Dr. Lisa Anderson",
      status: "active",
      startDate: "2024-05-12",
      instructions: "Follow prescribed exercises",
    },
  ],
  "patient-010": [
    {
      id: "rx-010-01",
      medicationName: "Antibiotics",
      dosage: "500mg",
      frequency: "Twice daily",
      duration: "2 weeks",
      prescribingDoctor: "Dr. Emily Rodriguez",
      status: "completed",
      startDate: "2024-04-20",
      endDate: "2024-05-04",
      instructions: "Complete full course",
    },
    {
      id: "rx-010-02",
      medicationName: "Pain Relief",
      dosage: "400mg",
      frequency: "Three times daily",
      duration: "2 weeks",
      prescribingDoctor: "Dr. Emily Rodriguez",
      status: "completed",
      startDate: "2024-04-20",
      endDate: "2024-05-04",
      instructions: "Take with food",
    },
  ],
  "patient-011": [
    {
      id: "rx-011-01",
      medicationName: "Salbutamol",
      dosage: "100mcg",
      frequency: "3-4 times daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. James Wilson",
      status: "active",
      startDate: "2024-02-25",
      instructions: "Use inhaler as needed",
    },
    {
      id: "rx-011-02",
      medicationName: "Ipratropium",
      dosage: "20mcg",
      frequency: "3-4 times daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. James Wilson",
      status: "active",
      startDate: "2024-02-25",
      instructions: "Use with spacer if possible",
    },
    {
      id: "rx-011-03",
      medicationName: "Prednisone",
      dosage: "10mg",
      frequency: "Once daily",
      duration: "1 week",
      prescribingDoctor: "Dr. James Wilson",
      status: "active",
      startDate: "2024-05-20",
      instructions: "Taper dose as directed",
    },
  ],
  "patient-012": [
    {
      id: "rx-012-01",
      medicationName: "Amlodipine",
      dosage: "5mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-03-30",
      instructions: "Monitor blood pressure",
    },
    {
      id: "rx-012-02",
      medicationName: "Losartan",
      dosage: "50mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-03-30",
      instructions: "Take at same time each day",
    },
    {
      id: "rx-012-03",
      medicationName: "Dietary Supplement",
      dosage: "1000mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Sarah Mitchell",
      status: "active",
      startDate: "2024-04-15",
      instructions: "Take with meals",
    },
  ],
  "patient-013": [
    {
      id: "rx-013-01",
      medicationName: "Tamsulosin",
      dosage: "0.4mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Anthony Martinez",
      status: "active",
      startDate: "2024-02-01",
      instructions: "Take 30 minutes after same meal each day",
    },
    {
      id: "rx-013-02",
      medicationName: "Finasteride",
      dosage: "5mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Anthony Martinez",
      status: "active",
      startDate: "2024-01-15",
      instructions: "Results may take 3-6 months",
    },
    {
      id: "rx-013-03",
      medicationName: "Citrulline Malate",
      dosage: "3000mg",
      frequency: "Once daily",
      duration: "Ongoing",
      prescribingDoctor: "Dr. Anthony Martinez",
      status: "active",
      startDate: "2024-03-10",
      instructions: "Take with water",
    },
  ],
}

// Mock Medical History Events
export const mockMedicalHistory: Record<string, MockMedicalHistoryEvent[]> = {
  "patient-001": [
    {
      type: "allergy",
      title: "Penicillin Allergy",
      description: "Severe allergic reaction - rash and swelling",
      date: "2020-06-15",
      severity: "severe",
    },
    {
      type: "condition",
      title: "Type 2 Diabetes",
      description: "Diagnosed with insulin-dependent diabetes",
      date: "2018-03-20",
      severity: "moderate",
    },
    {
      type: "surgery",
      title: "Appendectomy",
      description: "Emergency appendix removal",
      date: "2015-11-10",
    },
  ],
  "patient-002": [
    {
      type: "allergy",
      title: "Shellfish Allergy",
      description: "Anaphylaxis risk",
      date: "2019-08-22",
      severity: "severe",
    },
    {
      type: "condition",
      title: "Asthma",
      description: "Moderate persistent asthma",
      date: "2017-05-10",
      severity: "moderate",
    },
  ],
  "patient-003": [
    {
      type: "allergy",
      title: "Sulfa Drug Allergy",
      description: "Stevens-Johnson syndrome risk",
      date: "2016-02-14",
      severity: "severe",
    },
    {
      type: "condition",
      title: "Osteoarthritis",
      description: "Degenerative joint disease in knees and hips",
      date: "2019-01-05",
      severity: "moderate",
    },
    {
      type: "surgery",
      title: "Knee Replacement",
      description: "Total knee replacement - left knee",
      date: "2021-07-15",
    },
  ],
  "patient-004": [
    {
      type: "allergy",
      title: "NSAID Sensitivity",
      description: "Gastric irritation with ibuprofen",
      date: "2018-09-20",
      severity: "mild",
    },
    {
      type: "condition",
      title: "Chronic Migraines",
      description: "Migraines 2-3 times per week",
      date: "2015-04-10",
      severity: "moderate",
    },
  ],
  "patient-005": [
    {
      type: "allergy",
      title: "Latex Allergy",
      description: "Contact dermatitis and respiratory symptoms",
      date: "2017-11-30",
      severity: "moderate",
    },
    {
      type: "condition",
      title: "GERD",
      description: "Gastroesophageal reflux disease",
      date: "2016-03-15",
      severity: "mild",
    },
  ],
  "patient-006": [
    {
      type: "condition",
      title: "Hypothyroidism",
      description: "Primary hypothyroidism on replacement therapy",
      date: "2019-06-10",
      severity: "mild",
    },
  ],
  "patient-007": [
    {
      type: "allergy",
      title: "Aspirin Allergy",
      description: "Bronchospasm and angioedema",
      date: "2014-01-20",
      severity: "severe",
    },
    {
      type: "condition",
      title: "Coronary Artery Disease",
      description: "History of MI, stent placement",
      date: "2022-05-15",
      severity: "severe",
    },
    {
      type: "surgery",
      title: "Cardiac Stent",
      description: "Drug-eluting stent to left anterior descending artery",
      date: "2022-05-20",
    },
  ],
  "patient-008": [
    {
      type: "condition",
      title: "Type 1 Diabetes",
      description: "Insulin-dependent diabetes since childhood",
      date: "2010-02-01",
      severity: "moderate",
    },
    {
      type: "condition",
      title: "Chronic Kidney Disease",
      description: "Stage 3B CKD, eGFR 35",
      date: "2020-09-10",
      severity: "moderate",
    },
  ],
  "patient-009": [
    {
      type: "allergy",
      title: "Morphine Allergy",
      description: "Severe nausea and vomiting",
      date: "2023-01-15",
      severity: "severe",
    },
    {
      type: "surgery",
      title: "Fracture Repair",
      description: "Open reduction and internal fixation of femur",
      date: "2024-05-10",
    },
  ],
  "patient-010": [
    {
      type: "allergy",
      title: "Amoxicillin Allergy",
      description: "Rash develops within 12 hours",
      date: "2021-03-10",
      severity: "mild",
    },
  ],
  "patient-011": [
    {
      type: "allergy",
      title: "Dust Allergy",
      description: "Environmental trigger for asthma exacerbation",
      date: "2020-01-01",
      severity: "mild",
    },
    {
      type: "condition",
      title: "COPD",
      description: "Chronic obstructive pulmonary disease, Stage 3 Severe",
      date: "2018-11-20",
      severity: "severe",
    },
  ],
  "patient-012": [
    {
      type: "condition",
      title: "Essential Hypertension",
      description: "Stage 2 hypertension, on multiple medications",
      date: "2019-04-15",
      severity: "moderate",
    },
  ],
  "patient-013": [
    {
      type: "allergy",
      title: "Fluoroquinolone Allergy",
      description: "Tendon rupture risk",
      date: "2020-08-30",
      severity: "severe",
    },
    {
      type: "condition",
      title: "Benign Prostatic Hyperplasia",
      description: "BPH with lower urinary tract symptoms",
      date: "2021-12-01",
      severity: "mild",
    },
  ],
}

// Mock Lab Results
export const mockLabResults: Record<string, LabResult[]> = {
  "patient-001": [
    {
      _id: "lab-001-01",
      patientId: "patient-001",
      testType: "Blood Work",
      bodyPart: "General",
      imageUrl: "https://via.placeholder.com/200?text=Blood+Results",
      aiAnalysis: "Elevated glucose levels detected",
      status: "analyzed",
      doctorNotes: "Review glucose control, may need medication adjustment",
      createdAt: "2024-05-15T10:30:00Z",
    },
    {
      _id: "lab-001-02",
      patientId: "patient-001",
      testType: "Chest X-Ray",
      bodyPart: "Chest",
      imageUrl: "https://via.placeholder.com/200?text=Chest+XRay",
      aiAnalysis: "No acute findings",
      status: "reviewed",
      doctorNotes: "Heart size normal, lungs clear",
      createdAt: "2024-05-10T14:15:00Z",
    },
  ],
  "patient-002": [
    {
      _id: "lab-002-01",
      patientId: "patient-002",
      testType: "Pulmonary Function Test",
      bodyPart: "Lungs",
      imageUrl: "https://via.placeholder.com/200?text=PFT",
      aiAnalysis: "FEV1 reduced by 45%",
      status: "analyzed",
      doctorNotes: "Consistent with moderate asthma",
      createdAt: "2024-05-12T11:00:00Z",
    },
  ],
  "patient-003": [
    {
      _id: "lab-003-01",
      patientId: "patient-003",
      testType: "Knee X-Ray",
      bodyPart: "Knee - Left",
      imageUrl: "https://via.placeholder.com/200?text=Knee+XRay",
      aiAnalysis: "Post-op changes, alignment acceptable",
      status: "reviewed",
      doctorNotes: "Good prosthesis positioning",
      createdAt: "2024-05-20T09:45:00Z",
    },
  ],
  "patient-004": [
    {
      _id: "lab-004-01",
      patientId: "patient-004",
      testType: "MRI Brain",
      bodyPart: "Brain",
      imageUrl: "https://via.placeholder.com/200?text=Brain+MRI",
      aiAnalysis: "No structural abnormalities",
      status: "pending_review",
      doctorNotes: "Awaiting radiologist review",
      createdAt: "2024-05-21T13:20:00Z",
    },
  ],
  "patient-005": [
    {
      _id: "lab-005-01",
      patientId: "patient-005",
      testType: "Upper Endoscopy",
      bodyPart: "Esophagus/Stomach",
      imageUrl: "https://via.placeholder.com/200?text=Endoscopy",
      aiAnalysis: "Mild gastritis noted",
      status: "reviewed",
      doctorNotes: "Continue current treatment regimen",
      createdAt: "2024-05-18T08:30:00Z",
    },
  ],
}

export function getPatientById(patientId: string): User | undefined {
  return mockPatients.find((p) => p._id === patientId)
}

export function getPrescriptionsByPatientId(patientId: string): MockPrescription[] {
  return mockPrescriptions[patientId] || []
}

export function getMedicalHistoryByPatientId(
  patientId: string
): MockMedicalHistoryEvent[] {
  return mockMedicalHistory[patientId] || []
}

export function getLabResultsByPatientId(patientId: string): LabResult[] {
  return mockLabResults[patientId] || []
}

// =====================================================
// APPOINTMENTS DATA
// =====================================================

export interface MockAppointment {
  id: string
  patientId: string
  patientName: string
  doctorId: string
  doctorName: string
  department: string
  type: "consultation" | "follow-up" | "emergency" | "surgery" | "procedure"
  appointmentDate: string // YYYY-MM-DD
  startTime: string // HH:MM (24h)
  endTime: string // HH:MM (24h)
  status: "confirmed" | "pending" | "cancelled" | "completed" | "emergency"
  reason: string
  notes?: string
  room?: string
}

export interface MockDoctor {
  id: string
  name: string
  specialty: string
  department: string
  image?: string
  availableSlots: number
  nextAvailable: string // ISO datetime
  isAvailable: boolean
}

// Mock Appointments - Week of May 26-June 1, 2026
export const mockAppointments: MockAppointment[] = [
  // Monday, May 26
  {
    id: "apt-001",
    patientId: "patient-001",
    patientName: "Robert Johnson",
    doctorId: "doc-001",
    doctorName: "Dr. Sarah Mitchell",
    department: "Cardiology",
    type: "follow-up",
    appointmentDate: "2024-05-26",
    startTime: "09:00",
    endTime: "09:30",
    status: "confirmed",
    reason: "Blood pressure check",
    room: "Cardiology-A1",
  },
  {
    id: "apt-002",
    patientId: "patient-003",
    patientName: "Michael Chen",
    doctorId: "doc-003",
    doctorName: "Dr. Lisa Anderson",
    department: "Orthopedics",
    type: "consultation",
    appointmentDate: "2024-05-26",
    startTime: "10:00",
    endTime: "10:30",
    status: "confirmed",
    reason: "Post-surgery follow-up",
    room: "Ortho-C2",
  },
  {
    id: "apt-003",
    patientId: "patient-005",
    patientName: "Thomas Williams",
    doctorId: "doc-005",
    doctorName: "Dr. Rachel Green",
    department: "Gastroenterology",
    type: "follow-up",
    appointmentDate: "2024-05-26",
    startTime: "14:00",
    endTime: "14:30",
    status: "pending",
    reason: "Gastritis management review",
    notes: "Awaiting patient confirmation",
    room: "Gastro-B3",
  },

  // Tuesday, May 27
  {
    id: "apt-004",
    patientId: "patient-002",
    patientName: "Patricia Garcia",
    doctorId: "doc-002",
    doctorName: "Dr. James Wilson",
    department: "Pulmonology",
    type: "consultation",
    appointmentDate: "2024-05-27",
    startTime: "09:30",
    endTime: "10:00",
    status: "completed",
    reason: "Asthma evaluation",
    room: "Pulmo-A2",
  },
  {
    id: "apt-005",
    patientId: "patient-004",
    patientName: "Jennifer Martinez",
    doctorId: "doc-004",
    doctorName: "Dr. David Kumar",
    department: "Neurology",
    type: "follow-up",
    appointmentDate: "2024-05-27",
    startTime: "11:00",
    endTime: "11:30",
    status: "confirmed",
    reason: "Migraine management",
    room: "Neuro-C1",
  },
  {
    id: "apt-006",
    patientId: "patient-007",
    patientName: "David Lee",
    doctorId: "doc-001",
    doctorName: "Dr. Sarah Mitchell",
    department: "Cardiology",
    type: "emergency",
    appointmentDate: "2024-05-27",
    startTime: "15:00",
    endTime: "15:45",
    status: "emergency",
    reason: "Acute chest pain",
    notes: "Priority - ICU standby",
    room: "Cardiology-ER",
  },

  // Wednesday, May 28
  {
    id: "apt-007",
    patientId: "patient-006",
    patientName: "Angela Lopez",
    doctorId: "doc-006",
    doctorName: "Dr. Michael Torres",
    department: "Endocrinology",
    type: "consultation",
    appointmentDate: "2024-05-28",
    startTime: "09:00",
    endTime: "09:30",
    status: "confirmed",
    reason: "Thyroid medication adjustment",
    room: "Endo-A3",
  },
  {
    id: "apt-008",
    patientId: "patient-008",
    patientName: "Susan Brown",
    doctorId: "doc-007",
    doctorName: "Dr. Christopher Bell",
    department: "Nephrology",
    type: "procedure",
    appointmentDate: "2024-05-28",
    startTime: "13:00",
    endTime: "14:00",
    status: "confirmed",
    reason: "Renal function assessment",
    room: "Nephro-OR1",
  },
  {
    id: "apt-009",
    patientId: "patient-009",
    patientName: "Christopher Davis",
    doctorId: "doc-003",
    doctorName: "Dr. Lisa Anderson",
    department: "Orthopedics",
    type: "follow-up",
    appointmentDate: "2024-05-28",
    startTime: "16:00",
    endTime: "16:30",
    status: "cancelled",
    reason: "Fracture recovery check",
    notes: "Patient cancelled - rescheduled to June 4",
    room: "Ortho-C2",
  },

  // Thursday, May 29
  {
    id: "apt-010",
    patientId: "patient-010",
    patientName: "Rebecca White",
    doctorId: "doc-008",
    doctorName: "Dr. Emily Rodriguez",
    department: "Surgery",
    type: "follow-up",
    appointmentDate: "2024-05-29",
    startTime: "10:00",
    endTime: "10:30",
    status: "confirmed",
    reason: "Post-operative wound check",
    room: "Surgery-A1",
  },
  {
    id: "apt-011",
    patientId: "patient-011",
    patientName: "James Thompson",
    doctorId: "doc-002",
    doctorName: "Dr. James Wilson",
    department: "Pulmonology",
    type: "consultation",
    appointmentDate: "2024-05-29",
    startTime: "14:30",
    endTime: "15:00",
    status: "pending",
    reason: "COPD exacerbation review",
    room: "Pulmo-B2",
  },

  // Friday, May 30
  {
    id: "apt-012",
    patientId: "patient-012",
    patientName: "Laura Harris",
    doctorId: "doc-001",
    doctorName: "Dr. Sarah Mitchell",
    department: "Cardiology",
    type: "follow-up",
    appointmentDate: "2024-05-30",
    startTime: "09:30",
    endTime: "10:00",
    status: "confirmed",
    reason: "Hypertension management",
    room: "Cardiology-A1",
  },
  {
    id: "apt-013",
    patientId: "patient-013",
    patientName: "Richard Anderson",
    doctorId: "doc-009",
    doctorName: "Dr. Anthony Martinez",
    department: "Urology",
    type: "consultation",
    appointmentDate: "2024-05-30",
    startTime: "15:00",
    endTime: "15:30",
    status: "confirmed",
    reason: "Prostate health screening",
    room: "Urology-C3",
  },

  // Saturday, May 31
  {
    id: "apt-014",
    patientId: "patient-001",
    patientName: "Robert Johnson",
    doctorId: "doc-001",
    doctorName: "Dr. Sarah Mitchell",
    department: "Cardiology",
    type: "follow-up",
    appointmentDate: "2024-05-31",
    startTime: "11:00",
    endTime: "11:30",
    status: "confirmed",
    reason: "Weekly ECG check",
    room: "Cardiology-A2",
  },

  // Sunday, June 1
  {
    id: "apt-015",
    patientId: "patient-002",
    patientName: "Patricia Garcia",
    doctorId: "doc-002",
    doctorName: "Dr. James Wilson",
    department: "Pulmonology",
    type: "emergency",
    appointmentDate: "2024-06-01",
    startTime: "10:00",
    endTime: "10:45",
    status: "emergency",
    reason: "Breathing difficulty",
    notes: "After-hours emergency",
    room: "ER-Critical",
  },
]

// Mock Doctors with Availability
export const mockDoctors: MockDoctor[] = [
  {
    id: "doc-001",
    name: "Dr. Sarah Mitchell",
    specialty: "Cardiology",
    department: "Cardiology",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    availableSlots: 3,
    nextAvailable: "2024-05-26T11:00:00Z",
    isAvailable: true,
  },
  {
    id: "doc-002",
    name: "Dr. James Wilson",
    specialty: "Pulmonology",
    department: "Pulmonology",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=James",
    availableSlots: 2,
    nextAvailable: "2024-05-27T12:00:00Z",
    isAvailable: true,
  },
  {
    id: "doc-003",
    name: "Dr. Lisa Anderson",
    specialty: "Orthopedics",
    department: "Orthopedics",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa",
    availableSlots: 1,
    nextAvailable: "2024-05-28T14:30:00Z",
    isAvailable: true,
  },
  {
    id: "doc-004",
    name: "Dr. David Kumar",
    specialty: "Neurology",
    department: "Neurology",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    availableSlots: 4,
    nextAvailable: "2024-05-26T13:00:00Z",
    isAvailable: true,
  },
  {
    id: "doc-005",
    name: "Dr. Rachel Green",
    specialty: "Gastroenterology",
    department: "Gastroenterology",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rachel",
    availableSlots: 2,
    nextAvailable: "2024-05-29T09:00:00Z",
    isAvailable: false,
  },
  {
    id: "doc-006",
    name: "Dr. Michael Torres",
    specialty: "Endocrinology",
    department: "Endocrinology",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Michael",
    availableSlots: 5,
    nextAvailable: "2024-05-26T10:00:00Z",
    isAvailable: true,
  },
  {
    id: "doc-007",
    name: "Dr. Christopher Bell",
    specialty: "Nephrology",
    department: "Nephrology",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Christopher",
    availableSlots: 1,
    nextAvailable: "2024-05-30T11:00:00Z",
    isAvailable: true,
  },
  {
    id: "doc-008",
    name: "Dr. Emily Rodriguez",
    specialty: "Surgery",
    department: "Surgery",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    availableSlots: 0,
    nextAvailable: "2024-06-02T09:00:00Z",
    isAvailable: false,
  },
  {
    id: "doc-009",
    name: "Dr. Anthony Martinez",
    specialty: "Urology",
    department: "Urology",
    image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anthony",
    availableSlots: 3,
    nextAvailable: "2024-05-27T10:00:00Z",
    isAvailable: true,
  },
]

// Helper functions for appointments
export function getAppointmentsByDate(date: string): MockAppointment[] {
  return mockAppointments.filter((apt) => apt.appointmentDate === date)
}

export function getAppointmentsByDoctor(doctorId: string): MockAppointment[] {
  return mockAppointments.filter((apt) => apt.doctorId === doctorId)
}

export function getAppointmentsByStatus(
  status: MockAppointment["status"]
): MockAppointment[] {
  return mockAppointments.filter((apt) => apt.status === status)
}

export function getDoctorById(doctorId: string): MockDoctor | undefined {
  return mockDoctors.find((doc) => doc.id === doctorId)
}

export function getAppointmentsByDepartment(
  department: string
): MockAppointment[] {
  return mockAppointments.filter((apt) => apt.department === department)
}
